### ISSUE TITLE
Fail to catkin_make when following instructions in order

### ISSUE THREAD

**Issue by nicholasadr** [quangounet/osr_course_pkgs#6]
Website readers will face an error if they follow the website instructions in order (page-by-page). When running `catkin_make` under *Create a ROS workspace* in [System: ROS, Gazebo](https://crigroup.gitbooks.io/osrobotics/content/installation/system.html), the following error will occur:

```
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "openrave_catkin"
  with any of the following names:

    openrave_catkinConfig.cmake
    openrave_catkin-config.cmake

  Add the installation prefix of "openrave_catkin" to CMAKE_PREFIX_PATH or
  set "openrave_catkin_DIR" to a directory containing one of the above files.
  If "openrave_catkin" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  osr_course_pkgs/osr_openrave/CMakeLists.txt:4 (find_package)
```

This is due to instruction in [Basic tools](https://crigroup.gitbooks.io/osrobotics/content/installation/basic_tools.html) that tells user to clone the `osr_course_pkgs` without following immediately with instructions regarding dependencies which only appear later on in [System: ROS, Gazebo](https://crigroup.gitbooks.io/osrobotics/content/installation/system.html).

**Comment by kolking6** [comment]
What would be the fix? I can't seem to get mine to work. I ran the wstool code and failed at catkin_make with error 
[8%] Built target gazebo_ros_video
Makefile:138: recipe for target 'all' failed 
make:  *** [all] Error 2
Invoding "make install -j8 -l8" failed

**Comment by nicholasadr** [comment]
I realized that this issue should have been raised in another repository. Hence closing this.
